In [1]:
!module --ignore_cache load python/3.9.6
!pip uninstall torch -y
!pip uninstall transformers -y
!rm -r ~/.local/lib/python3.9/site-packages/torch-2.0.1+computecanada.dist-info/
!pip install ~/torch-2.0.1+computecanada-cp39-cp39-linux_x86_64.whl
!pip install numpy==1.24.4 tqdm scikit-learn torch==2.0.1 transformers==4.37.1 rich

/bin/bash: line 1: module: command not found
Found existing installation: torch 2.0.1
Uninstalling torch-2.0.1:
  Successfully uninstalled torch-2.0.1
Found existing installation: transformers 4.37.1
Uninstalling transformers-4.37.1:
  Successfully uninstalled transformers-4.37.1
rm: cannot remove '/home/vbertalan/.local/lib/python3.9/site-packages/torch-2.0.1+computecanada.dist-info/': No such file or directory
Defaulting to user installation because normal site-packages is not writeable
ERROR: torch-2.0.1+computecanada-cp39-cp39-linux_x86_64.whl is not a supported wheel on this platform.
Defaulting to user installation because normal site-packages is not writeable
  Using cached torch-2.0.1-cp310-cp310-manylinux1_x86_64.whl.metadata (24 kB)
  Using cached transformers-4.37.1-py3-none-any.whl.metadata (129 kB)
Using cached torch-2.0.1-cp310-cp310-manylinux1_x86_64.whl (619.9 MB)
Using cached transformers-4.37.1-py3-none-any.whl (8.4 MB)


In [2]:
import sys
sys.path.append("..")
import linetracker.main as m
import linetracker.parser.parser as p
import linetracker.embeddings.llm as llm_embedding
import linetracker.embeddings.distances as d
import linetracker.line_distance as ld
import linetracker.parser.variables_matrix as ev
import linetracker.clustering.kmedoid as clustK

import numpy as np
import h5py
import json
import time
import tqdm
from rich.console import Console

/home/vbertalan/.local/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


## 1. Get example log files

```python
splits = m2.get_split_build_logs("../data/splitted_event_ids.json")# type: ignore
print("Sizes available: ",np.unique([len(s) for s in splits.values()]))
```
```
Sizes available:  [  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  75
  77 127 129 130 131 132 145 147 148]
```

```python
# get log file of size specified
sizes = [2, 3, 10, 148]
splits_samples = {}
with h5py.File("../data/trat3_production_1650_1700_20231411_v1.hdf5") as fp:
    splits_samples = {}
    for k,split in splits.items():
        if len(split) not in sizes or len(split) in splits_samples:
            continue
        L = []
        for e in tqdm.tqdm(split):
            L.append({**fp[e].attrs})
        splits_samples[len(split)] = [k,L]
```
```
  0%|          | 0/10 [00:00<?, ?it/s]
100%|██████████| 10/10 [00:00<00:00, 31.80it/s]
100%|██████████| 2/2 [00:00<00:00, 38.69it/s]
100%|██████████| 3/3 [00:00<00:00, 38.14it/s]
100%|██████████| 148/148 [00:03<00:00, 45.37it/s]
```

```python
class CustomEncoder(json.JSONEncoder):
    def default(self, obj):
        print(type(obj),obj)
        if isinstance(obj, np.int32):
            return int(obj)
        if isinstance(obj, np.ndarray):
            return self.default(obj.tolist())
        if isinstance(obj, list):
            return [self.default(e) for e in obj.tolist()]
        if isinstance(obj, dict):
            return {k:self.default(v) for k,v in obj.items()}
        else:
            return obj

with open("./data.json", "w") as fp:
    json.dump(splits_samples, fp, cls=CustomEncoder)

## 2. Execute the pipeline

In [3]:
with open("data.json") as fp:
    splits_samples = json.load(fp)
splits_samples = {k:v for k,v in sorted(splits_samples.items(),key=lambda x:int(x[0]))}
print(list(splits_samples.keys()))

['2', '3', '10', '148']


We have the doc

```python
def execute_full_pipeline(
    logs: List[LogData],
    triplet_coefficient: TripletCoef,
    parser: Callable[[List[LogData]], List[p.ParsedLine]],
    embedder: Callable[[List[str]], Generator[np.ndarray, None, None]],
    embedding_distance_fn: Callable[[List[np.ndarray]], np.ndarray],
    line_distance_fn: Callable[[List[LogData]], np.ndarray],
    clustering_fn: Callable[[np.ndarray], c.ClusteringAlgorithmOutput],
    float_precision: type = np.float32,
) -> c.ClusteringAlgorithmOutput:
    """Cluster logs provided in argument into groups of related log lines
    # Arguments
    - logs: List[LogData], the log lines
    - triplet_coefficient: TripletCoef, the three coefficients to use to ponderate the matrices
    - parser: Callable[[List[LogData]], List[p.ParsedLine]], a function that from the list of logs lines can generate for each line
    - embedder: Callable[[List[str]], Generator[np.ndarray, None, None]], the function that can generate embeddings from logs
    - embedding_distance_fn: Callable[[List[np.ndarray]], np.ndarray], given all embeddings of each log lines of the same log file, generate the normalized (between 0 and 1) distances between all embeddings
    - line_distance_fn: Callable[[List[str]],np.ndarray], a function that can generate a matrix with the distance between each log line
    - clustering_fn:  Callable[[np.ndarray], c.ClusteringAlgorithmOutput], taking the combined matrix with the coefficients provided, clusters the logs
    - float_precision: type = np.float32, the precision to use for all floating point matrices
    """
```

In [4]:
# build the functions for the pipeline
parser = lambda logs:p.get_parsing_drainparser([e['text'] for e in logs],depth=3,similarity_threshold=0.1,max_children=5)
models_names = ["meta-llama/Llama-2-7b-chat-hf","WhereIsAI/UAE-Large-V1", "BAAI/bge-large-en-v1.5"]
model_name = models_names[2]
init_embedder = llm_embedding.generate_embeddings_llm(model_name=model_name,token="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", use_cpu=True)
pooling_fn = llm_embedding.get_pooling_function("mean")
embedder = lambda logs: init_embedder(logs, pooling_fn,limit_tokens=100,precision=np.float16)# type: ignore
embedding_distance_fn = d.normalized_cosine_distance
line_distance_fn = ld.get_absolute_line_distance_matrix
clustering_fn = lambda combined_matrix: clustK.get_clustering_kmedoid(combined_matrix)[0]['clustering']
float_precision = np.float16
triplet_coefficient = m.TripletCoef(coef_variables_matrix=0.4, coef_embeddings_matrix=0.6, coef_count_matrix=0.0)

Token will not been saved to git credential helper. Pass `add_to_git_credential=True` if you want to set the git credential as well.
Token is valid (permission: write).
Your token has been saved to /home/vbertalan/.cache/huggingface/token
Login successful


If you want to use `BertLMHeadModel` as a standalone, add `is_decoder=True.`


Token will not been saved to git credential helper. Pass `add_to_git_credential=True` if you want to set the git credential as well.
Token is valid (permission: write).
Your token has been saved to /home/vbertalan/.cache/huggingface/token
Login successful


Some weights of BertLMHeadModel were not initialized from the model checkpoint at BAAI/bge-large-en-v1.5 and are newly initialized: ['cls.predictions.bias', 'cls.predictions.decoder.bias', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


We will execute each step of the pipeline:
```python
    # 1. parse the logs
    parsed_logs: List[p.ParsedLine] = parser(logs)
    logs_texts = [e["text"] for e in logs]
    parsed_variables = [e["variables"] for e in parsed_logs]
    # 2. build the variable matrix (alreay normalized matrix as it has values between 0 and 1)
    variables_distance_matrix = e.get_variable_matrix(parsed_variables).astype(float_precision)
    # 3. build the embeddings
    embeddings: List[np.ndarray] = [embedding for embedding in embedder(logs_texts)]
    # 4. build the distance matrix
    embeddings_distance_matrix = embedding_distance_fn(embeddings).astype(
        float_precision
    )
    del embeddings
    # 5. build the count matrix
    count_matrix = line_distance_fn(logs).astype(float_precision)
    # 6. merge the matrices with triplet coefficient
    combined_matrix = combine_matrices(
        TripletMatrix(
            variables_matrix=variables_distance_matrix,
            embeddings_matrix=embeddings_distance_matrix,
            count_matrix=count_matrix,
        ),
        triplet_coef=triplet_coefficient,
    ).astype(float_precision)
    # note: values will be between 0 and 3 (addition of 3 matrices normalized between 0 and 3)
    del variables_distance_matrix
    del embeddings_distance_matrix
    # 7. run the clustering algorithm with the constraints
    clustering_output = clustering_fn(combined_matrix)
    # 8. return the result
    return clustering_output
```

First step:
```python
    # 1. parse the logs
    parsed_logs: List[p.ParsedLine] = parser(logs)
    logs_texts = [e["text"] for e in logs]
    parsed_variables = [e["variables"] for e in parsed_logs]
```

In [5]:
dict_parsed_variables = {}
# for each of our log file with different number of lines, we apply step 1 and save the result
for size,[build_log_name, logs] in splits_samples.items():
    print(f"{build_log_name:-^100}")
    parsed_logs = parser(logs)
    # Apply step 1
    logs_texts = [e['text'] for e in logs]
    parsed_variables = [e['variables'] for e in parsed_logs]
    # Show the result (truncated)
    for i,(text, variables) in enumerate(zip(logs_texts, parsed_variables)):
        print(variables,": ",text)
        if i > 10:
            print("...")
            break
    # And save the result
    dict_parsed_variables[size] = parsed_variables

----------------------------------------243909--TCSBASE6_ppc----------------------------------------
[] :  2023-11-03 06:51:16 sed: can't read dw_stubsA.d: No such file or directory

[] :  2023-11-03 06:52:10 ldppc: BFD 2.15 assertion fail ../../binutils-2.15/bfd/linker.c:619

------------------------------------244245--COREBASE69_SPAP3_sim------------------------------------
['14:20:06'] :  2023-11-05 14:20:06 make[2]: cleartool: Command not found

['14:20:07'] :  2023-11-05 14:20:07 make[2]: cleartool: Command not found

[] :  cp: cannot stat '/localdisk/6500_repo/ome/vobs/equinox_ne_build/basebuild/EQBASE/sim/COREBASE69_SPAP3/*elf': No such file or directory

------------------------------------------242344--otsc_ppc------------------------------------------
['sed:', "can't read *.h.temp:"] :  2023-10-27 07:05:36 sed: can't read *.h.temp: No such file or directory

['07:06:21'] :  2023-10-27 07:06:21 tput: No value for $TERM and no -T specified

['07:05:36'] :  2023-10-27 07:05:36 t

Then step2: 
```python
    # 2. build the variable matrix (alreay normalized matrix as it has values between 0 and 1)
    variables_distance_matrix = e.get_variable_matrix(parsed_variables).astype(float_precision)
```

In [6]:
dict_variables_distance_matrix = {}
for size,parsed_variables in dict_parsed_variables.items():
    variables_distance_matrix = ev.get_variable_matrix(parsed_events=parsed_variables)
    dict_variables_distance_matrix[size] = variables_distance_matrix
    print(f"{size:-^100}")
    for i,v in enumerate(parsed_variables):
        print(i,":",v)
        if i > 10:
            print("...")
            break
    print(dict_variables_distance_matrix[size])
    print("-"*100)  

-------------------------------------------------2--------------------------------------------------
0 : []
1 : []
[[0. 0.]
 [0. 0.]]
----------------------------------------------------------------------------------------------------
-------------------------------------------------3--------------------------------------------------
0 : ['14:20:06']
1 : ['14:20:07']
2 : []
[[0. 1. 1.]
 [1. 0. 1.]
 [1. 1. 0.]]
----------------------------------------------------------------------------------------------------
-------------------------------------------------10-------------------------------------------------
0 : ['sed:', "can't read *.h.temp:"]
1 : ['07:06:21']
2 : ['07:05:36']
3 : ['07:05:36']
4 : ['07:05:14']
5 : ['07:05:35']
6 : ['07:05:14']
7 : ['07:06:21']
8 : ['mv:', "cannot stat '*.h':"]
9 : ['07:05:35']
[[0. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 1. 1. 1. 1. 1. 0. 1. 1.]
 [1. 1. 0. 0. 1. 1. 1. 1. 1. 1.]
 [1. 1. 0. 0. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 0. 1. 0. 1. 1. 1.]
 [1. 1. 1. 1

Then step 3
```python
    # 1. parse the logs
    parsed_logs: List[p.ParsedLine] = parser(logs)
    logs_texts = [e["text"] for e in logs]
    parsed_variables = [e["variables"] for e in parsed_logs]
    # 2. build the variable matrix (alreay normalized matrix as it has values between 0 and 1)
    variables_distance_matrix = e.get_variable_matrix(parsed_variables).astype(float_precision)
    # 3. build the embeddings
    embeddings: np.ndarray = np.array(
        [embedding for embedding in embedder(logs_texts)]
    ).astype(float_precision)
    # 4. build the distance matrix
    embeddings_distance_matrix = embedding_distance_fn(embeddings).astype(
        float_precision
    )
    del embeddings
```

In [7]:
%%time
dict_embeddings_distance_matrix = {}
for size,[build_log_name, logs] in splits_samples.items():
    print(f"{size:-^100}")
    logs_texts = [e['text'] for e in logs]
    start = time.perf_counter()
    embeddings = np.array(
        [embedding for embedding in embedder(logs_texts)]
    ).astype(float_precision)
    diff = time.perf_counter()-start
    print(f"{embeddings.shape=}, obtained in {diff} second ({diff/embeddings.shape[0]} s/embedding)")
    embeddings_distance_matrix = embedding_distance_fn(embeddings).astype(
        float_precision
    )
    print("*"*100)
    print(embeddings_distance_matrix)
    dict_embeddings_distance_matrix[size] = embeddings_distance_matrix
    del embeddings

-------------------------------------------------2--------------------------------------------------
embeddings.shape=(2, 30522), obtained in 0.375411428976804 second (0.187705714488402 s/embedding)
****************************************************************************************************
[[0.     0.2148]
 [0.2148 0.    ]]
-------------------------------------------------3--------------------------------------------------
embeddings.shape=(3, 30522), obtained in 0.33814104995690286 second (0.11271368331896763 s/embedding)
****************************************************************************************************
[[0.000e+00 7.844e-05 2.761e-01]
 [7.844e-05 0.000e+00 2.756e-01]
 [2.761e-01 2.756e-01 0.000e+00]]
-------------------------------------------------10-------------------------------------------------
embeddings.shape=(10, 30522), obtained in 1.0567538579925895 second (0.10567538579925895 s/embedding)
**********************************************************


```python
    # 1. parse the logs
    parsed_logs: List[p.ParsedLine] = parser(logs)
    logs_texts = [e["text"] for e in logs]
    parsed_variables = [e["variables"] for e in parsed_logs]
    # 2. build the variable matrix (alreay normalized matrix as it has values between 0 and 1)
    variables_distance_matrix = e.get_variable_matrix(parsed_variables).astype(float_precision)
    # 3. build the embeddings
    embeddings: List[np.ndarray] = [embedding for embedding in embedder(logs_texts)]
    # 4. build the distance matrix
    embeddings_distance_matrix = embedding_distance_fn(embeddings).astype(
        float_precision
    )
    del embeddings
    # 5. build the count matrix
    count_matrix = line_distance_fn(logs).astype(float_precision)
```

In [8]:
%%time
splits_samples = {k:splits_samples[k] for k in sorted(splits_samples)}#type: ignore
dict_count_matrix = {}
for size,[build_log_name, logs] in splits_samples.items():
    print(f"{size:-^100}")
    count_matrix = line_distance_fn(logs).astype(float_precision)
    dict_count_matrix[size] = count_matrix
    print(count_matrix)

-------------------------------------------------10-------------------------------------------------
[[0.     0.1111 0.2222 0.3333 0.4443 0.5557 0.6665 0.778  0.8887 1.    ]
 [0.1111 0.     0.1111 0.2222 0.3333 0.4443 0.5557 0.6665 0.778  0.8887]
 [0.2222 0.1111 0.     0.1111 0.2222 0.3333 0.4443 0.5557 0.6665 0.778 ]
 [0.3333 0.2222 0.1111 0.     0.1111 0.2222 0.3333 0.4443 0.5557 0.6665]
 [0.4443 0.3333 0.2222 0.1111 0.     0.1111 0.2222 0.3333 0.4443 0.5557]
 [0.5557 0.4443 0.3333 0.2222 0.1111 0.     0.1111 0.2222 0.3333 0.4443]
 [0.6665 0.5557 0.4443 0.3333 0.2222 0.1111 0.     0.1111 0.2222 0.3333]
 [0.778  0.6665 0.5557 0.4443 0.3333 0.2222 0.1111 0.     0.1111 0.2222]
 [0.8887 0.778  0.6665 0.5557 0.4443 0.3333 0.2222 0.1111 0.     0.1111]
 [1.     0.8887 0.778  0.6665 0.5557 0.4443 0.3333 0.2222 0.1111 0.    ]]
------------------------------------------------148-------------------------------------------------
[[0.     0.0068 0.0136 ... 0.9863 0.993  1.    ]
 [0.0068 0.     0.

```python
    # 1. parse the logs
    parsed_logs: List[p.ParsedLine] = parser(logs)
    logs_texts = [e["text"] for e in logs]
    parsed_variables = [e["variables"] for e in parsed_logs]
    # 2. build the variable matrix (alreay normalized matrix as it has values between 0 and 1)
    variables_distance_matrix = e.get_variable_matrix(parsed_variables).astype(float_precision)
    # 3. build the embeddings
    embeddings: np.ndarray = np.array(
        [embedding for embedding in embedder(logs_texts)]
    ).astype(float_precision)
    # 4. build the distance matrix
    embeddings_distance_matrix = embedding_distance_fn(embeddings).astype(
        float_precision
    )
    del embeddings
    # 5. build the count matrix
    count_matrix = line_distance_fn(logs).astype(float_precision)
    # 6. merge the matrices with triplet coefficient
    combined_matrix = combine_matrices(
        TripletMatrix(
            variables_matrix=variables_distance_matrix,
            embeddings_matrix=embeddings_distance_matrix,
            count_matrix=count_matrix,
        ),
        triplet_coef=triplet_coefficient,
    ).astype(float_precision)
    # note: values will be between 0 and 3 (addition of 3 matrices normalized between 0 and 3)
    del variables_distance_matrix
    del embeddings_distance_matrix
```

In [9]:
dico_combined_matrix = {}
for size in dict_count_matrix:
    print(size)
    for i,mat in enumerate([dict_variables_distance_matrix[size],dict_embeddings_distance_matrix[size],dict_count_matrix[size]]):
        assert np.unique(np.diag(mat)).tolist() == [0], f"Error for matrix {i}\n{mat}"
    dico_combined_matrix[size] = m.combine_matrices(
        m.TripletMatrix(
            variables_matrix=dict_variables_distance_matrix[size],
            embeddings_matrix=dict_embeddings_distance_matrix[size],
            count_matrix=dict_count_matrix[size],
        ),
        triplet_coef=triplet_coefficient,
    ).astype(float_precision)
    

10
148
2
3


To finally have
```python
    # 1. parse the logs
    parsed_logs: List[p.ParsedLine] = parser(logs)
    logs_texts = [e["text"] for e in logs]
    parsed_variables = [e["variables"] for e in parsed_logs]
    # 2. build the variable matrix (alreay normalized matrix as it has values between 0 and 1)
    variables_distance_matrix = e.get_variable_matrix(parsed_variables).astype(float_precision)
    # 3. build the embeddings
    embeddings: np.ndarray = np.array(
        [embedding for embedding in embedder(logs_texts)]
    ).astype(float_precision)
    # 4. build the distance matrix
    embeddings_distance_matrix = embedding_distance_fn(embeddings).astype(
        float_precision
    )
    del embeddings
    # 5. build the count matrix
    count_matrix = line_distance_fn(logs).astype(float_precision)
    # 6. merge the matrices with triplet coefficient
    combined_matrix = combine_matrices(
        TripletMatrix(
            variables_matrix=variables_distance_matrix,
            embeddings_matrix=embeddings_distance_matrix,
            count_matrix=count_matrix,
        ),
        triplet_coef=triplet_coefficient,
    ).astype(float_precision)
    # note: values will be between 0 and 3 (addition of 3 matrices normalized between 0 and 3)
    del variables_distance_matrix
    del embeddings_distance_matrix
    # 7. run the clustering algorithm with the constraints
    clustering_output = clustering_fn(combined_matrix)
    # 8. return the result
    return clustering_output
```

In [11]:
dico_clustering_output = {}
for size,matrix in dico_combined_matrix.items():
    print(np.diag(matrix))
    dico_clustering_output[size] = clustering_fn(matrix)
    

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


AssertionError: Expecting number_of_clusters=2 or less but found len(unique_clusters)=8 with unique_clusters=array([4.00193173e-322, 4.74303020e-321, 2.12199579e-314, 4.64674638e-310,
       4.64794701e-310, 4.64794767e-310, 4.64794807e-310, 6.94168483e-310]) clusters=array([2.12199579e-314, 2.12199579e-314, 2.12199579e-314, 4.00193173e-322,
       6.94168483e-310, 4.64794701e-310, 4.64794767e-310, 4.64794807e-310,
       4.64674638e-310, 4.74303020e-321])
combined_matrix.reshape((n_points, n_dims)).tolist()=[[0.0, 0.51904296875, 0.5205078125, 0.5205078125, 0.521484375, 0.51953125, 0.521484375, 0.51904296875, 0.47705078125, 0.51953125], [0.51904296875, 0.0, 0.400146484375, 0.400146484375, 0.400146484375, 0.400146484375, 0.400146484375, 0.0, 0.57080078125, 0.400146484375], [0.5205078125, 0.400146484375, 0.0, 0.0, 0.400146484375, 0.400146484375, 0.400146484375, 0.400146484375, 0.57275390625, 0.400146484375], [0.5205078125, 0.400146484375, 0.0, 0.0, 0.400146484375, 0.400146484375, 0.400146484375, 0.400146484375, 0.57275390625, 0.400146484375], [0.521484375, 0.400146484375, 0.400146484375, 0.400146484375, 0.0, 0.400146484375, 0.0, 0.400146484375, 0.57421875, 0.400146484375], [0.51953125, 0.400146484375, 0.400146484375, 0.400146484375, 0.400146484375, 0.0, 0.400146484375, 0.400146484375, 0.572265625, 0.0], [0.521484375, 0.400146484375, 0.400146484375, 0.400146484375, 0.0, 0.400146484375, 0.0, 0.400146484375, 0.57421875, 0.400146484375], [0.51904296875, 0.0, 0.400146484375, 0.400146484375, 0.400146484375, 0.400146484375, 0.400146484375, 0.0, 0.57080078125, 0.400146484375], [0.47705078125, 0.57080078125, 0.57275390625, 0.57275390625, 0.57421875, 0.572265625, 0.57421875, 0.57080078125, 0.0, 0.572265625], [0.51953125, 0.400146484375, 0.400146484375, 0.400146484375, 0.400146484375, 0.0, 0.400146484375, 0.400146484375, 0.572265625, 0.0]]

Finally we show the text with each cluster

In [11]:
import colorsys

def generate_hsv_palette(num_colors, saturation=1.0, value=1.0):
    colors = []
    hue_step = 1.0 / num_colors

    for i in range(num_colors):
        hue = i * hue_step
        rgb = colorsys.hsv_to_rgb(hue, saturation, value)
        rgb = tuple(int(x * 255) for x in rgb)
        colors.append(rgb)

    return colors



In [12]:
console = Console(color_system="auto", highlight=False, force_jupyter=True)
dico_clustering_output = {s:dico_clustering_output[s] for s in sorted(dico_clustering_output,key=lambda x:int(x))}
print(list(dico_clustering_output.keys()))
for size, _ in dico_clustering_output.items():
    console.print(f"{size:-^100}", style=f"white", end="" )
    clustering_output = list(dico_clustering_output[size].values())
    unique_clusters =  np.unique(clustering_output)
    mapping = {clust:col for clust,col in zip(unique_clusters,generate_hsv_palette(len(unique_clusters),saturation=0.75))}
    for line_id, (log,cluster) in enumerate(zip(splits_samples[size][1], clustering_output)):
        text = f"{line_id:03d}-{cluster}: {log['text']}"
        r,g,b = mapping[cluster]
        console.print(text, style=f"rgb({r},{g},{b})", end="" )

['2', '3', '10', '148']


-------------------------------------------------2--------------------------------------------------

000-0: 2023-11-03 06:51:16 sed: can't read dw_stubsA.d: No such file or directory

001-1: 2023-11-03 06:52:10 ldppc: BFD 2.15 assertion fail ../../binutils-2.15/bfd/linker.c:619

-------------------------------------------------3--------------------------------------------------

000-1.0: 2023-11-05 14:20:06 make[2]: cleartool: Command not found

001-1.0: 2023-11-05 14:20:07 make[2]: cleartool: Command not found

002-2.0: cp: cannot stat 
'/localdisk/6500_repo/ome/vobs/equinox_ne_build/basebuild/EQBASE/sim/COREBASE69_SPAP3/*elf': No such file or 
directory

-------------------------------------------------10-------------------------------------------------

000-1.0: 2023-10-27 07:05:36 sed: can't read *.h.temp: No such file or directory

001-1.0: 2023-10-27 07:06:21 tput: No value for $TERM and no -T specified

002-2.0: 2023-10-27 07:05:36 tput: No value for $TERM and no -T specified

003-2.0: 2023-10-27 07:05:36 tput: No value for $TERM and no -T specified

004-1.0: 2023-10-27 07:05:14 tput: No value for $TERM and no -T specified

005-1.0: 2023-10-27 07:05:35 tput: No value for $TERM and no -T specified

006-1.0: 2023-10-27 07:05:14 tput: No value for $TERM and no -T specified

007-1.0: 2023-10-27 07:06:21 tput: No value for $TERM and no -T specified

008-1.0: 2023-10-27 07:05:36 mv: cannot stat '*.h': No such file or directory

009-1.0: 2023-10-27 07:05:35 tput: No value for $TERM and no -T specified

------------------------------------------------148-------------------------------------------------

000-32.0: 2023-10-19 15:25:11 6.3 compile failed using  .. 

001-1.0: 2023-10-19 15:42:46 microsvc/src/qsfpdd/plugctrl_cdb_dd.c:330:42: invalid suffix "b100" on integer 
constant

002-2.0: 2023-10-19 15:31:10 
/localdisk/6500_repo/ome/vobs/optnet_core/include/./rtos/vxWorks/vxWorks_6.x/../../../../../optnet_os/vxworks/vxwor
ks-6.9/target/h/sys/types.h:134:39: base/b_pthread_condattr_t.h: No such file or directory

003-35.0: 2023-10-19 15:31:29 /localdisk/6500_repo/ome/vobs/optnet_os/vxworks//vxworks-6.9/target/h/taskLib.h:789: 
error: `tCurrent' undeclared (first use in this function)

004-4.0: 2023-10-19 15:33:28 
/localdisk/6500_repo/ome/vobs/optnet_os/vxworks//vxworks-6.9/target/h/semaphoreCommon.h:84: error: conflicting 
types for '_Restrict'

005-5.0: cp: cannot stat 
'/localdisk/6500_repo/ome/vobs/viking_otn_apps/common_utils/ddf/system/vxworks/vx69/*compile_cmds*log': No such 
file or directory

006-6.0: 2023-10-19 15:42:46 microsvc/src/qsfpdd/plugctrl_cdb_dd.c:538:19: invalid suffix "b00000100" on integer 
constant

007-51.0: 2023-10-19 15:25:11 ==============FAIL =================

008-32.0: 2023-10-19 15:25:11 6.3 compile failed using  .. 

009-9.0: cp: cannot stat '/localdisk/6500_repo/ome/vobs/viking_otn_apps/common_utils/ddf/system/vxworks/vx69/*SWD':
No such file or directory

010-63.0: 2023-10-19 15:25:11 cc1: error: unrecognized command line option "-Werror=sign-compare"

011-30.0: 2023-10-19 15:32:15 /localdisk/6500_repo/ome/vobs/optnet_os/vxworks//vxworks-6.9/target/h/taskLib.h:789: 
error: for each function it appears in.)

012-12.0: 2023-10-19 15:31:20 /localdisk/6500_repo/ome/vobs/optnet_os/vxworks//vxworks-6.9/target/h/signal.h:370: 
error: syntax error before "REG_SET"

013-13.0: 2023-10-19 15:31:20 
/localdisk/6500_repo/ome/vobs/optnet_os/vxworks//vxworks-6.9/target/h/base/b_trace_id_t.h:34: error: syntax error 
before "trace_id_t"

014-14.0: 2023-10-19 15:31:10 
/localdisk/6500_repo/ome/vobs/optnet_core/include/./rtos/vxWorks/vxWorks_6.x/../../../../../optnet_os/vxworks/vxwor
ks-6.9/target/h/sys/types.h:131:30: base/b_clockid_t.h: No such file or directory

015-63.0: 2023-10-19 15:25:11 cc1: error: unrecognized command line option "-Werror=sign-compare"

016-70.0: 2023-10-19 15:32:40 /localdisk/6500_repo/ome/vobs/optnet_os/vxworks//vxworks-6.9/target/h/taskLib.h:789: 
error: (Each undeclared identifier is reported only once

017-17.0: 2023-10-19 15:42:46 microsvc/src/qsfpdd/plugctrl_cdb_dd.c:328:42: invalid suffix "b010" on integer 
constant

018-18.0: cp: cannot stat 
'/localdisk/6500_repo/ome/vobs/viking_otn_apps/common_utils/ddf/system/vxworks/vx69/*config/ome*.objs.log': No such
file or directory

019-38.0: 2023-10-19 15:31:10 
/localdisk/6500_repo/ome/vobs/optnet_os/vxworks//vxworks-6.9/target/h/base/b_trace_id_t.h:34: error: syntax error 
before "trace_id_t"

020-50.0: 2023-10-19 15:31:20 
/localdisk/6500_repo/ome/vobs/optnet_os/vxworks//vxworks-6.9/target/h/private/taskLibP.h:373: error: `pTcb' 
undeclared (first use in this function)

021-21.0: 2023-10-19 15:31:20 /localdisk/6500_repo/ome/vobs/optnet_os/vxworks//vxworks-6.9/target/h/taskLib.h:505: 
error: syntax error before "REG_SET"

022-30.0: 2023-10-19 15:32:40 /localdisk/6500_repo/ome/vobs/optnet_os/vxworks//vxworks-6.9/target/h/taskLib.h:789: 
error: for each function it appears in.)

023-23.0: 2023-10-19 15:31:10 /localdisk/6500_repo/extensions/ddf/plugsdk/ddf-generator/scripts/genxmlreg.sh: line 
2: toolsetup: command not found

024-24.0: cp: cannot stat 
'/localdisk/6500_repo/ome/vobs/viking_otn_apps/common_utils/ddf/system/vxworks/vx69/*vk_product_mk_vars_*list': No 
such file or directory

025-70.0: 2023-10-19 15:32:31 /localdisk/6500_repo/ome/vobs/optnet_os/vxworks//vxworks-6.9/target/h/taskLib.h:789: 
error: (Each undeclared identifier is reported only once

026-59.0: 2023-10-19 15:42:46 microsvc/src/qsfpdd/plugctrl_cdb_dd.c:557:20: invalid suffix "b00000001" on integer 
constant

027-30.0: 2023-10-19 15:32:31 /localdisk/6500_repo/ome/vobs/optnet_os/vxworks//vxworks-6.9/target/h/taskLib.h:789: 
error: for each function it appears in.)

028-28.0: 2023-10-19 15:25:12 ==============FAIL =================

029-29.0: 2023-10-19 15:33:29 /localdisk/6500_repo/ome/vobs/optnet_os/vxworks//vxworks-6.9/target/h/fcntl.h:56: 
error: previous declaration of 'open' was here

030-30.0: 2023-10-19 15:31:48 /localdisk/6500_repo/ome/vobs/optnet_os/vxworks//vxworks-6.9/target/h/taskLib.h:789: 
error: for each function it appears in.)

031-32.0: | 15:58:05:        21757  'Server returned: 400 {\'_content\': 
b\'{"error":"ValueError","error_string":"Version could not be converted to float: 2023.10.19.14.53.76"}\\n\', 
\'_content_consumed\': True, \'_next\': None, \'status_code\': 400, \'headers\': {\'Server\': \'nginx\', \'Date\': 
\'Thu, 19 Oct 2023  GMT\', \'Content-Type\': \'application/json\', \'Content-Length\': \'101\', \'Connection\': 
\'keep-alive\', \'Keep-Alive\': \'timeout=75\'}, \'raw\': <urllib3.response.HTTPResponse object at 0x7f09e3d0c610>,
\'url\': \'https://6500.ciena.com/pftools/api/toolsmetric/\', \'encoding\': \'utf-8\', \'history\': [], \'reason\':
\'BAD REQUEST\', \'cookies\': <RequestsCookieJar[]>, \'elapsed\': datetime.timedelta(microseconds=36951), 
\'request\': <PreparedRequest [POST]>, \'connection\': <requests.adapters.HTTPAdapter object at 0x7f09e3c44790>}'

032-32.0: 2023-10-19 15:25:12 6.3 compile failed using  .. 

033-146.0: 2023-10-19 15:25:10 find: ‘/localdisk/6500_repo/ddy-messaging/yang’: No such file or directory

034-50.0: 2023-10-19 15:31:30 
/localdisk/6500_repo/ome/vobs/optnet_os/vxworks//vxworks-6.9/target/h/private/taskLibP.h:355: error: `pTcb' 
undeclared (first use in this function)

035-35.0: 2023-10-19 15:31:29 /localdisk/6500_repo/ome/vobs/optnet_os/vxworks//vxworks-6.9/target/h/taskLib.h:841: 
error: `tCurrent' undeclared (first use in this function)

036-35.0: 2023-10-19 15:31:20 /localdisk/6500_repo/ome/vobs/optnet_os/vxworks//vxworks-6.9/target/h/taskLib.h:789: 
error: `tCurrent' undeclared (first use in this function)

037-37.0: 2023-10-19 15:31:20 /localdisk/6500_repo/ome/vobs/optnet_os/vxworks//vxworks-6.9/target/h/selectLib.h:96:
error: syntax error before '}' token

038-38.0: 2023-10-19 15:31:10 
/localdisk/6500_repo/ome/vobs/optnet_os/vxworks//vxworks-6.9/target/h/base/b_trace_id_t.h:34: error: syntax error 
before "trace_id_t"

039-39.0: 2023-10-19 15:25:10 find: ‘/localdisk/6500_repo/service-broker/yang’: No such file or directory

040-40.0: 2023-10-19 15:31:30 
/localdisk/6500_repo/ome/vobs/optnet_os/vxworks//vxworks-6.9/target/h/private/hookTblLibP.h:35: error: requested 
alignment is not a constant

041-41.0: 2023-10-19 15:42:46 microsvc/src/qsfpdd/plugctrl_cdb_dd.c:328: error: enumerator value for 
`PLUGCTRL_DD_MODULESTATE_POWER_UP' not integer constant

042-51.0: 2023-10-19 15:25:11 ==============FAIL =================

043-146.0: 2023-10-19 15:25:10 find: ‘/localdisk/6500_repo/ddm-tcp/yang’: No such file or directory

044-63.0: 2023-10-19 15:25:11 cc1: error: unrecognized command line option "-Werror=sign-compare"

045-45.0: 2023-10-19 15:25:09 jq: error (at <stdin>:19): null (null) has no keys

046-46.0: 2023-10-19 15:31:20 /localdisk/6500_repo/ome/vobs/optnet_os/vxworks//vxworks-6.9/target/h/taskLib.h:1072:
error: syntax error before "REG_SET"

047-47.0: 2023-10-19 15:42:46 microsvc/src/qsfpdd/plugctrl_cdb_dd.c:327: error: enumerator value for 
`PLUGCTRL_DD_MODULESTATE_LOW_POWER' not integer constant

048-53.0: 2023-10-19 15:31:39 
/localdisk/6500_repo/ome/vobs/optnet_os/vxworks//vxworks-6.9/target/h/private/semLibP.h:153: error: requested 
alignment is not a constant

049-49.0: 2023-10-19 15:31:20 /localdisk/6500_repo/ome/vobs/optnet_os/vxworks//vxworks-6.9/target/h/taskLib.h:710: 
error: syntax error before '}' token

050-50.0: 2023-10-19 15:31:20 
/localdisk/6500_repo/ome/vobs/optnet_os/vxworks//vxworks-6.9/target/h/private/taskLibP.h:355: error: `pTcb' 
undeclared (first use in this function)

051-51.0: 2023-10-19 15:25:11 ==============FAIL =================

052-52.0: 2023-10-19 15:56:47 cannot open directory: grub.d

053-53.0: 2023-10-19 15:31:29 
/localdisk/6500_repo/ome/vobs/optnet_os/vxworks//vxworks-6.9/target/h/private/semLibP.h:153: error: requested 
alignment is not a constant

054-54.0: 2023-10-19 15:31:10 
/localdisk/6500_repo/ome/vobs/optnet_core/include/./rtos/vxWorks/vxWorks_6.x/../../../../../optnet_os/vxworks/vxwor
ks-6.9/target/h/sys/types.h:139:32: base/b_suseconds_t.h: No such file or directory

055-55.0: 2023-10-19 15:42:46 microsvc/src/qsfpdd/plugctrl_cdb_dd.c:329: error: enumerator value for 
`PLUGCTRL_DD_MODULESTATE_READY' not integer constant

056-56.0: 2023-10-19 15:42:46 microsvc/src/qsfpdd/plugctrl_cdb_dd.c:331:42: invalid suffix "b101" on integer 
constant

057-57.0: 2023-10-19 15:42:46 microsvc/src/qsfpdd/plugctrl_cdb_dd.c:329:42: invalid suffix "b011" on integer 
constant

058-32.0: 'Server returned: 400 {\'_content\': b\'{"error":"ValueError","error_string":"Version could not be 
converted to float: 2023.10.19.14.53.76"}\\n\', \'_content_consumed\': True, \'_next\': None, \'status_code\': 400,
\'headers\': {\'Server\': \'nginx\', \'Date\': \'Thu, 19 Oct 2023 19:57:58 GMT\', \'Content-Type\': 
\'application/json\', \'Content-Length\': \'101\', \'Connection\': \'keep-alive\', \'Keep-Alive\': \'timeout=75\'},
\'raw\': <urllib3.response.HTTPResponse object at 0x7f09e3d0c610>, \'url\': 
\'https://6500.ciena.com/pftools/api/toolsmetric/\', \'encoding\': \'utf-8\', \'history\': [], \'reason\': \'BAD 
REQUEST\', \'cookies\': <RequestsCookieJar[]>, \'elapsed\': datetime.timedelta(microseconds=36951), \'request\': 
<PreparedRequest [POST]>, \'connection\': <requests.adapters.HTTPAdapter object at 0x7f09e3c44790>}'

059-59.0: 2023-10-19 15:42:46 microsvc/src/qsfpdd/plugctrl_cdb_dd.c:518:19: invalid suffix "b00000001" on integer 
constant

060-146.0: 2023-10-19 15:25:10 find: ‘/localdisk/6500_repo/plug-controller/yang’: No such file or directory

061-61.0: cp: cannot stat 
'/localdisk/6500_repo/ome/vobs/viking_otn_apps/common_utils/ddf/system/vxworks/vx69/*raw': No such file or 
directory

062-70.0: 2023-10-19 15:31:39 /localdisk/6500_repo/ome/vobs/optnet_os/vxworks//vxworks-6.9/target/h/taskLib.h:789: 
error: (Each undeclared identifier is reported only once

063-63.0: 2023-10-19 15:25:11 cc1: error: unrecognized command line option "-Werror=sign-compare"

064-145.0: 2023-10-19 15:31:20 
/localdisk/6500_repo/ome/vobs/optnet_os/vxworks//vxworks-6.9/target/h/taskLib.h:1048: error: syntax error before 
'*' token

065-65.0: 2023-10-19 15:42:46 microsvc/src/qsfpdd/plugctrl_cdb_dd.c:326: error: enumerator value for 
`PLUGCTRL_DD_MODULESTATE_RESERVED' not integer constant

066-32.0: 2023-10-19 15:25:11 6.3 compile failed using  .. 

067-63.0: 2023-10-19 15:25:11 cc1: error: unrecognized command line option "-Werror=sign-compare"

068-51.0: 2023-10-19 15:25:11 ==============FAIL =================

069-69.0: 2023-10-19 15:31:10 
/localdisk/6500_repo/ome/vobs/optnet_core/include/./rtos/vxWorks/vxWorks_6.x/../../../../../optnet_os/vxworks/vxwor
ks-6.9/target/h/sys/types.h:84:26: types/vxCpuX.h: No such file or directory

070-70.0: 2023-10-19 15:32:23 /localdisk/6500_repo/ome/vobs/optnet_os/vxworks//vxworks-6.9/target/h/taskLib.h:789: 
error: (Each undeclared identifier is reported only once

071-40.0: 2023-10-19 15:31:48 
/localdisk/6500_repo/ome/vobs/optnet_os/vxworks//vxworks-6.9/target/h/private/hookTblLibP.h:35: error: requested 
alignment is not a constant

072-72.0: cp: cannot stat 
'/localdisk/6500_repo/ome/vobs/viking_otn_apps/common_utils/ddf/system/vxworks/vx69/*map': No such file or 
directory

073-73.0: 2023-10-19 15:42:46 microsvc/src/qsfpdd/plugctrl_cdb_dd.c:327:42: invalid suffix "b001" on integer 
constant

074-35.0: 2023-10-19 15:31:30 
/localdisk/6500_repo/ome/vobs/optnet_os/vxworks//vxworks-6.9/target/h/private/taskLibP.h:598: error: `tCurrent' 
undeclared (first use in this function)

075-70.0: 2023-10-19 15:32:15 /localdisk/6500_repo/ome/vobs/optnet_os/vxworks//vxworks-6.9/target/h/taskLib.h:789: 
error: (Each undeclared identifier is reported only once

076-30.0: 2023-10-19 15:31:20 /localdisk/6500_repo/ome/vobs/optnet_os/vxworks//vxworks-6.9/target/h/taskLib.h:789: 
error: for each function it appears in.)

077-145.0: 2023-10-19 15:31:20 /localdisk/6500_repo/ome/vobs/optnet_os/vxworks//vxworks-6.9/target/h/taskLib.h:719:
error: syntax error before '*' token

078-145.0: 2023-10-19 15:31:20 /localdisk/6500_repo/ome/vobs/optnet_os/vxworks//vxworks-6.9/target/h/taskLib.h:837:
error: syntax error before '*' token

079-79.0: 2023-10-19 15:31:10 
/localdisk/6500_repo/ome/vobs/optnet_core/include/./rtos/vxWorks/vxWorks_6.x/../../../../../optnet_os/vxworks/vxwor
ks-6.9/target/h/sys/types.h:136:36: base/b_pthread_mutex_t.h: No such file or directory

080-30.0: 2023-10-19 15:31:55 /localdisk/6500_repo/ome/vobs/optnet_os/vxworks//vxworks-6.9/target/h/taskLib.h:789: 
error: for each function it appears in.)

081-40.0: 2023-10-19 15:31:20 
/localdisk/6500_repo/ome/vobs/optnet_os/vxworks//vxworks-6.9/target/h/private/hookTblLibP.h:35: error: requested 
alignment is not a constant

082-82.0: 2023-10-19 15:42:46 microsvc/src/qsfpdd/plugctrl_cdb_dd.c:528:19: invalid suffix "b00000010" on integer 
constant

083-83.0: 2023-10-19 15:44:10 
/localdisk/6500_repo/ome/vobs/optnet_os/vxworks//vxworks-6.9/target/h/semaphoreCommon.h:83: error: previous 
definition of '_Restrict' was here

084-30.0: 2023-10-19 15:31:29 /localdisk/6500_repo/ome/vobs/optnet_os/vxworks//vxworks-6.9/target/h/taskLib.h:789: 
error: for each function it appears in.)

085-35.0: 2023-10-19 15:31:20 
/localdisk/6500_repo/ome/vobs/optnet_os/vxworks//vxworks-6.9/target/h/private/taskLibP.h:598: error: `tCurrent' 
undeclared (first use in this function)

086-86.0: 2023-10-19 15:25:12 cc1: error: unrecognized command line option "-Werror=sign-compare"

087-87.0: 2023-10-19 15:56:47 cannot open directory: dhcp

088-88.0: 2023-10-19 15:42:46 microsvc/src/qsfpdd/plugctrl_cdb_dd.c:330: error: enumerator value for 
`PLUGCTRL_DD_MODULESTATE_POWER_DOWN' not integer constant

089-89.0: cp: cannot stat 
'/localdisk/6500_repo/ome/vobs/viking_otn_apps/common_utils/ddf/system/vxworks/vx69/*elf': No such file or 
directory

090-53.0: 2023-10-19 15:32:05 
/localdisk/6500_repo/ome/vobs/optnet_os/vxworks//vxworks-6.9/target/h/private/semLibP.h:153: error: requested 
alignment is not a constant

091-32.0: | 15:57:58: Exception creating new tools metrics record:

092-92.0: cp: cannot stat 
'/localdisk/6500_repo/ome/vobs/viking_otn_apps/common_utils/ddf/system/vxworks/vx69/*bin': No such file or 
directory

093-14.0: 2023-10-19 15:31:10 
/localdisk/6500_repo/ome/vobs/optnet_core/include/./rtos/vxWorks/vxWorks_6.x/../../../../../optnet_os/vxworks/vxwor
ks-6.9/target/h/sys/types.h:131:30: base/b_clockid_t.h: No such file or directory

094-32.0: 2023-10-19 15:25:11 6.3 compile failed using  .. 

095-95.0: 2023-10-19 15:31:10 
/localdisk/6500_repo/ome/vobs/optnet_core/include/./rtos/vxWorks/vxWorks_6.x/../../../../../optnet_os/vxworks/vxwor
ks-6.9/target/h/sys/types.h:135:34: base/b_pthread_key_t.h: No such file or directory

096-96.0: 2023-10-19 15:42:46 microsvc/src/qsfpdd/plugctrl_cdb_dd.c:331: error: enumerator value for 
`PLUGCTRL_DD_MODULESTATE_FAULT' not integer constant

097-51.0: 2023-10-19 15:25:11 ==============FAIL =================

098-51.0: 2023-10-19 15:25:11 ==============FAIL =================

099-40.0: 2023-10-19 15:31:39 
/localdisk/6500_repo/ome/vobs/optnet_os/vxworks//vxworks-6.9/target/h/private/hookTblLibP.h:35: error: requested 
alignment is not a constant

100-32.0: 2023-10-19 15:25:10 6.3 compile failed using  .. 

101-38.0: 2023-10-19 15:31:10 
/localdisk/6500_repo/ome/vobs/optnet_os/vxworks//vxworks-6.9/target/h/base/b_trace_id_t.h:34: error: syntax error 
before "trace_id_t"

102-53.0: 2023-10-19 15:31:55 
/localdisk/6500_repo/ome/vobs/optnet_os/vxworks//vxworks-6.9/target/h/private/semLibP.h:153: error: requested 
alignment is not a constant

103-53.0: 2023-10-19 15:31:48 
/localdisk/6500_repo/ome/vobs/optnet_os/vxworks//vxworks-6.9/target/h/private/semLibP.h:153: error: requested 
alignment is not a constant

104-29.0: 2023-10-19 15:33:29 /localdisk/6500_repo/ome/vobs/optnet_os/vxworks//vxworks-6.9/target/h/fcntl.h:56: 
error: previous declaration of 'open' was here

105-105.0: cp: cannot stat 
'/localdisk/6500_repo/ome/vobs/viking_otn_apps/common_utils/ddf/system/vxworks/vx69/*warning.count': No such file 
or directory

106-70.0: 2023-10-19 15:31:29 /localdisk/6500_repo/ome/vobs/optnet_os/vxworks//vxworks-6.9/target/h/taskLib.h:789: 
error: (Each undeclared identifier is reported only once

107-107.0: 2023-10-19 15:33:29 /localdisk/6500_repo/ome/vobs/optnet_os/vxworks//vxworks-6.9/target/h/ioLib.h:471: 
error: conflicting types for 'open'

108-32.0: 2023-10-19 15:25:11 6.3 compile failed using  .. 

109-109.0: 2023-10-19 15:25:10 ==============FAIL =================

110-83.0: 2023-10-19 15:33:28 
/localdisk/6500_repo/ome/vobs/optnet_os/vxworks//vxworks-6.9/target/h/semaphoreCommon.h:83: error: previous 
definition of '_Restrict' was here

111-70.0: 2023-10-19 15:32:05 /localdisk/6500_repo/ome/vobs/optnet_os/vxworks//vxworks-6.9/target/h/taskLib.h:789: 
error: (Each undeclared identifier is reported only once

112-63.0: 2023-10-19 15:25:11 cc1: error: unrecognized command line option "-Werror=sign-compare"

113-145.0: 2023-10-19 15:31:20 /localdisk/6500_repo/ome/vobs/optnet_os/vxworks//vxworks-6.9/target/h/taskLib.h:784:
error: syntax error before '*' token

114-70.0: 2023-10-19 15:31:55 /localdisk/6500_repo/ome/vobs/optnet_os/vxworks//vxworks-6.9/target/h/taskLib.h:789: 
error: (Each undeclared identifier is reported only once

115-51.0: 2023-10-19 15:25:11 ==============FAIL =================

116-32.0: 2023-10-19 15:25:11 6.3 compile failed using  .. 

117-53.0: 2023-10-19 15:31:20 
/localdisk/6500_repo/ome/vobs/optnet_os/vxworks//vxworks-6.9/target/h/private/semLibP.h:153: error: requested 
alignment is not a constant

118-63.0: 2023-10-19 15:25:11 cc1: error: unrecognized command line option "-Werror=sign-compare"

119-38.0: 2023-10-19 15:31:10 
/localdisk/6500_repo/ome/vobs/optnet_os/vxworks//vxworks-6.9/target/h/base/b_trace_id_t.h:34: error: syntax error 
before "trace_id_t"

120-120.0: 2023-10-19 15:31:10 
/localdisk/6500_repo/ome/vobs/optnet_core/include/./rtos/vxWorks/vxWorks_6.x/../../../../../optnet_os/vxworks/vxwor
ks-6.9/target/h/sys/types.h:137:40: base/b_pthread_mutexattr_t.h: No such file or directory

121-107.0: 2023-10-19 15:33:29 /localdisk/6500_repo/ome/vobs/optnet_os/vxworks//vxworks-6.9/target/h/ioLib.h:471: 
error: conflicting types for 'open'

122-122.0: cp: cannot stat 
'/localdisk/6500_repo/ome/vobs/viking_otn_apps/common_utils/ddf/system/vxworks/vx69/**.sizes': No such file or 
directory

123-51.0: 2023-10-19 15:25:11 ==============FAIL =================

124-37.0: 2023-10-19 15:31:20 
/localdisk/6500_repo/ome/vobs/optnet_os/vxworks//vxworks-6.9/target/h/selectLib.h:103: error: syntax error before 
'}' token

125-125.0: 2023-10-19 15:31:20 
/localdisk/6500_repo/ome/vobs/optnet_os/vxworks//vxworks-6.9/target/h/taskLib.h:1071: error: syntax error before 
"REG_SET"

126-50.0: 2023-10-19 15:31:30 
/localdisk/6500_repo/ome/vobs/optnet_os/vxworks//vxworks-6.9/target/h/private/taskLibP.h:373: error: `pTcb' 
undeclared (first use in this function)

127-30.0: 2023-10-19 15:31:39 /localdisk/6500_repo/ome/vobs/optnet_os/vxworks//vxworks-6.9/target/h/taskLib.h:789: 
error: for each function it appears in.)

128-128.0: 2023-10-19 15:31:10 
/localdisk/6500_repo/ome/vobs/optnet_core/include/./rtos/vxWorks/vxWorks_6.x/../../../../../optnet_os/vxworks/vxwor
ks-6.9/target/h/sys/types.h:133:35: base/b_pthread_cond_t.h: No such file or directory

129-63.0: 2023-10-19 15:25:11 cc1: error: unrecognized command line option "-Werror=sign-compare"

130-70.0: 2023-10-19 15:31:20 /localdisk/6500_repo/ome/vobs/optnet_os/vxworks//vxworks-6.9/target/h/taskLib.h:789: 
error: (Each undeclared identifier is reported only once

131-70.0: 2023-10-19 15:31:48 /localdisk/6500_repo/ome/vobs/optnet_os/vxworks//vxworks-6.9/target/h/taskLib.h:789: 
error: (Each undeclared identifier is reported only once

132-132.0: 2023-10-19 15:31:20 
/localdisk/6500_repo/ome/vobs/optnet_os/vxworks//vxworks-6.9/target/h/selectLib.h:91: error: syntax error before 
"WIND_TCB"

133-146.0: 2023-10-19 15:25:10 find: ‘/localdisk/6500_repo/broadband/yang’: No such file or directory

134-134.0: 2023-10-19 15:42:46 microsvc/src/qsfpdd/plugctrl_cdb_dd.c:326:42: invalid suffix "b000" on integer 
constant

135-49.0: 2023-10-19 15:31:20 /localdisk/6500_repo/ome/vobs/optnet_os/vxworks//vxworks-6.9/target/h/signal.h:372: 
error: syntax error before '}' token

136-86.0: 2023-10-19 15:25:12 cc1: error: unrecognized command line option "-Werror=sign-compare"

137-137.0: 2023-10-19 15:44:10 
/localdisk/6500_repo/ome/vobs/optnet_os/vxworks//vxworks-6.9/target/h/semaphoreCommon.h:84: error: conflicting 
types for '_Restrict'

138-30.0: 2023-10-19 15:32:05 /localdisk/6500_repo/ome/vobs/optnet_os/vxworks//vxworks-6.9/target/h/taskLib.h:789: 
error: for each function it appears in.)

139-146.0: 2023-10-19 15:25:10 find: ‘/localdisk/6500_repo/ddy-db/yang’: No such file or directory

140-32.0: 2023-10-19 15:25:12 6.3 compile failed using  .. 

141-32.0: 2023-10-19 15:25:11 6.3 compile failed using  .. 

142-30.0: 2023-10-19 15:32:23 /localdisk/6500_repo/ome/vobs/optnet_os/vxworks//vxworks-6.9/target/h/taskLib.h:789: 
error: for each function it appears in.)

143-69.0: 2023-10-19 15:31:10 
/localdisk/6500_repo/ome/vobs/optnet_core/include/./rtos/vxWorks/vxWorks_6.x/../../../../../optnet_os/vxworks/vxwor
ks-6.9/target/h/sys/types.h:84:26: types/vxCpuX.h: No such file or directory

144-35.0: 2023-10-19 15:31:20 /localdisk/6500_repo/ome/vobs/optnet_os/vxworks//vxworks-6.9/target/h/taskLib.h:841: 
error: `tCurrent' undeclared (first use in this function)

145-145.0: 2023-10-19 15:31:20 
/localdisk/6500_repo/ome/vobs/optnet_os/vxworks//vxworks-6.9/target/h/taskLib.h:1056: error: syntax error before 
'*' token

146-146.0: 2023-10-19 15:25:10 find: ‘/localdisk/6500_repo/ddy-diag/yang’: No such file or directory

147-145.0: 2023-10-19 15:31:20 
/localdisk/6500_repo/ome/vobs/optnet_os/vxworks//vxworks-6.9/target/h/taskLib.h:1066: error: syntax error before 
'*' token